export type Job = {
  id: string
  title: string
  company: string
  location: string
  mode: 'Remote' | 'Hybrid' | 'Onsite'
  experience: 'Fresher' | '0-1' | '1-3' | '3-5'
  skills: string[]
  source: 'LinkedIn' | 'Naukri' | 'Indeed'
  postedDaysAgo: number
  salaryRange: string
  applyUrl: string
  description: string
}

export const jobs: Job[] = [
  {
    id: 'job-1',
    title: 'SDE Intern',
    company: 'Amazon India',
    location: 'Bengaluru, Karnataka',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Java', 'DSA', 'OOP', 'REST APIs'],
    source: 'LinkedIn',
    postedDaysAgo: 0,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.linkedin.com/jobs/view/amazon-sde-intern-1',
    description:
      'Work with a small backend team on customer-facing services.\nContribute to low-risk features under guidance from senior engineers.\nParticipate in code reviews and learn Amazon engineering standards.\nIdeal for final-year students comfortable with Java and data structures.',
  },
  {
    id: 'job-2',
    title: 'Frontend Intern',
    company: 'Flipkart',
    location: 'Bengaluru, Karnataka',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['JavaScript', 'React', 'HTML', 'CSS'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.linkedin.com/jobs/view/flipkart-frontend-intern-2',
    description:
      'Assist in building customer-facing React components for the storefront.\nWork closely with designers to translate Figma mocks into pixel-perfect UI.\nWrite clean, reusable code with attention to accessibility and performance.\nGreat fit for students who have built at least one React project.',
  },
  {
    id: 'job-3',
    title: 'Graduate Engineer Trainee',
    company: 'Infosys',
    location: 'Pune, Maharashtra',
    mode: 'Onsite',
    experience: '0-1',
    skills: ['Java', 'SQL', 'Spring', 'Problem Solving'],
    source: 'Naukri',
    postedDaysAgo: 2,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.naukri.com/job-listings-infosys-get-java-3',
    description:
      'Join the Infosys training program and rotate across delivery teams.\nLearn enterprise Java, databases, and SDLC practices on live projects.\nCollaborate with senior developers to understand client requirements.\nSuitable for 2023–2025 graduates with basic Java and SQL knowledge.',
  },
  {
    id: 'job-4',
    title: 'Java Developer (0-1 years)',
    company: 'TCS',
    location: 'Hyderabad, Telangana',
    mode: 'Onsite',
    experience: '0-1',
    skills: ['Core Java', 'Spring Boot', 'REST', 'MySQL'],
    source: 'Naukri',
    postedDaysAgo: 3,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.naukri.com/job-listings-tcs-java-developer-4',
    description:
      'Work on internal tools and client modules built on Spring Boot.\nWrite REST APIs, unit tests, and help maintain existing services.\nPair with senior engineers to understand TCS coding and deployment standards.\nIdeal for freshers with good Java fundamentals and willingness to learn.',
  },
  {
    id: 'job-5',
    title: 'Python Developer (Fresher)',
    company: 'Wipro',
    location: 'Chennai, Tamil Nadu',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Python', 'Django', 'REST APIs', 'PostgreSQL'],
    source: 'Indeed',
    postedDaysAgo: 4,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.indeed.co.in/viewjob-wipro-python-fresher-5',
    description:
      'Contribute to backend services for internal dashboards.\nWork with Django and PostgreSQL under guidance from senior developers.\nWrite simple features, bug fixes, and basic automation scripts.\nGood for freshers who have completed at least one Django project.',
  },
  {
    id: 'job-6',
    title: 'React Developer (1-3 years)',
    company: 'Zoho',
    location: 'Chennai, Tamil Nadu',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['React', 'TypeScript', 'Redux', 'REST APIs'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://www.linkedin.com/jobs/view/zoho-react-developer-6',
    description:
      'Build and maintain frontends for Zoho SaaS products.\nWork closely with product designers to ship clean, accessible UI.\nOwn small features end-to-end with clear metrics for success.\nPreferred for engineers with 1–3 years of React experience.',
  },
  {
    id: 'job-7',
    title: 'Junior Backend Developer',
    company: 'Freshworks',
    location: 'Chennai, Tamil Nadu',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Node.js', 'Express', 'MongoDB', 'REST APIs'],
    source: 'LinkedIn',
    postedDaysAgo: 5,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://www.linkedin.com/jobs/view/freshworks-junior-backend-7',
    description:
      'Support core backend services that power customer support tools.\nImplement endpoints, write tests, and help with performance tuning.\nCollaborate with frontend teams to design stable API contracts.\nSuitable for developers with 1–3 years of Node.js experience.',
  },
  {
    id: 'job-8',
    title: 'Data Analyst Intern',
    company: 'Razorpay',
    location: 'Bengaluru, Karnataka',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['SQL', 'Excel', 'Python', 'Dashboards'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.linkedin.com/jobs/view/razorpay-data-analyst-intern-8',
    description:
      'Work with the analytics team to monitor payment funnel metrics.\nCreate simple dashboards and reports for business stakeholders.\nClean and analyse transaction data using SQL and Python notebooks.\nIdeal for students comfortable with SQL joins and basic statistics.',
  },
  {
    id: 'job-9',
    title: 'QA Intern',
    company: 'PhonePe',
    location: 'Bengaluru, Karnataka',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Manual Testing', 'Test Cases', 'JIRA'],
    source: 'Indeed',
    postedDaysAgo: 6,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.indeed.co.in/viewjob-phonepe-qa-intern-9',
    description:
      'Help test new features for the consumer app before release.\nWrite and execute test cases on Android and iOS builds.\nLog issues clearly with steps, screenshots, and expected behaviour.\nGood for freshers interested in starting a QA or SDET career path.',
  },
  {
    id: 'job-10',
    title: 'SDE Intern',
    company: 'CRED',
    location: 'Bengaluru, Karnataka',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Kotlin', 'Android', 'REST APIs'],
    source: 'LinkedIn',
    postedDaysAgo: 0,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.linkedin.com/jobs/view/cred-sde-android-intern-10',
    description:
      'Contribute to small Android features and internal tooling.\nWork with senior Android engineers on code reviews and refactors.\nHelp improve app performance and stability on mid-range devices.\nIdeal for final-year students with at least one published Android app.',
  },
  {
    id: 'job-11',
    title: 'Junior Backend Developer',
    company: 'Juspay',
    location: 'Bengaluru, Karnataka',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Java', 'Kotlin', 'Microservices', 'PostgreSQL'],
    source: 'LinkedIn',
    postedDaysAgo: 3,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://www.linkedin.com/jobs/view/juspay-junior-backend-11',
    description:
      'Join a small payments team responsible for high-volume APIs.\nWork on latency-sensitive services with strong reliability standards.\nParticipate in design discussions and post-release reviews.\nBest suited for engineers comfortable with Java/Kotlin and SQL.',
  },
  {
    id: 'job-12',
    title: 'React Developer (1-3 years)',
    company: 'Cognizant',
    location: 'Pune, Maharashtra',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['React', 'TypeScript', 'Redux', 'REST'],
    source: 'Naukri',
    postedDaysAgo: 4,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://www.naukri.com/job-listings-cognizant-react-developer-12',
    description:
      'Work on enterprise dashboards for global clients.\nImplement reusable React components aligned with the design system.\nCoordinate with backend teams to consume secure APIs.\nGood fit for engineers with 1–3 years in modern React.',
  },
  {
    id: 'job-13',
    title: 'SDE Intern',
    company: 'Paytm',
    location: 'Noida, Uttar Pradesh',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Java', 'Spring', 'Microservices'],
    source: 'LinkedIn',
    postedDaysAgo: 7,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.linkedin.com/jobs/view/paytm-sde-intern-13',
    description:
      'Assist in building microservices for wallet and payments flows.\nWrite small features, bug fixes, and integration tests.\nLearn how large-scale systems are monitored and deployed.\nIdeal for students strong in Java and interested in distributed systems.',
  },
  {
    id: 'job-14',
    title: 'Graduate Engineer Trainee',
    company: 'Capgemini',
    location: 'Mumbai, Maharashtra',
    mode: 'Onsite',
    experience: '0-1',
    skills: ['Java', 'SQL', 'HTML', 'CSS'],
    source: 'Naukri',
    postedDaysAgo: 5,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.naukri.com/job-listings-capgemini-get-14',
    description:
      'Rotate across Java, web, and testing teams during the first year.\nWork under mentorship on internal tools and client deliverables.\nGain exposure to SDLC, documentation, and client communication.\nOpen to 2023–2024 graduates from CS/IT branches.',
  },
  {
    id: 'job-15',
    title: 'Python Developer (Fresher)',
    company: 'Accenture',
    location: 'Hyderabad, Telangana',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Python', 'Flask', 'SQL', 'Git'],
    source: 'Indeed',
    postedDaysAgo: 2,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.indeed.co.in/viewjob-accenture-python-fresher-15',
    description:
      'Help build automation scripts and small web tools for internal teams.\nWork with Flask, SQL, and REST APIs in a structured environment.\nWrite maintainable code with attention to logging and error handling.\nGreat starting role for Python enthusiasts entering consulting.',
  },
  {
    id: 'job-16',
    title: 'Data Analyst Intern',
    company: 'Swiggy',
    location: 'Bengaluru, Karnataka',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['SQL', 'Excel', 'Tableau', 'Python'],
    source: 'LinkedIn',
    postedDaysAgo: 3,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.linkedin.com/jobs/view/swiggy-data-analyst-intern-16',
    description:
      'Work with city teams to monitor delivery time and cancellation metrics.\nBuild simple visualisations in Tableau and maintain weekly reports.\nClean data extracts using SQL and Python notebooks.\nPerfect for final-year students with strong analytical skills.',
  },
  {
    id: 'job-17',
    title: 'Junior Backend Developer',
    company: 'PhonePe',
    location: 'Bengaluru, Karnataka',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Java', 'Spring Boot', 'Kafka', 'MySQL'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://www.linkedin.com/jobs/view/phonepe-junior-backend-17',
    description:
      'Help build high-volume APIs for payments and rewards features.\nContribute to design, implementation, and incident reviews.\nWork closely with SRE teams to ensure reliability and latency goals.\nSuitable for engineers with payments or fintech exposure.',
  },
  {
    id: 'job-18',
    title: 'React Developer (1-3 years)',
    company: 'Freshworks',
    location: 'Chennai, Tamil Nadu',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['React', 'TypeScript', 'Design Systems'],
    source: 'LinkedIn',
    postedDaysAgo: 4,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://www.linkedin.com/jobs/view/freshworks-react-developer-18',
    description:
      'Build UI for customer engagement and support products.\nUse internal design systems to deliver consistent experiences.\nWork in cross-functional squads with PMs and designers.\nIdeal for developers who care about UX and accessibility.',
  },
  {
    id: 'job-19',
    title: 'SDE Intern',
    company: 'Razorpay',
    location: 'Bengaluru, Karnataka',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Go', 'Java', 'Microservices'],
    source: 'LinkedIn',
    postedDaysAgo: 6,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.linkedin.com/jobs/view/razorpay-sde-intern-19',
    description:
      'Contribute to backend services that handle payment routing.\nShadow senior engineers during design and incident reviews.\nShip small features with clear test coverage and monitoring.\nGood for students familiar with strongly typed languages.',
  },
  {
    id: 'job-20',
    title: 'Frontend Intern',
    company: 'Zoho',
    location: 'Chennai, Tamil Nadu',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['JavaScript', 'React', 'CSS', 'Testing'],
    source: 'Indeed',
    postedDaysAgo: 8,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.indeed.co.in/viewjob-zoho-frontend-intern-20',
    description:
      'Support UI teams in building new modules for SaaS products.\nFix front-end bugs and improve component behaviour.\nLearn how design reviews and accessibility checks are done.\nSuited for freshers with strong JavaScript basics.',
  },
  {
    id: 'job-21',
    title: 'Java Developer (0-1 years)',
    company: 'Oracle India',
    location: 'Bengaluru, Karnataka',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Java', 'Spring', 'REST', 'SQL'],
    source: 'Naukri',
    postedDaysAgo: 2,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://www.naukri.com/job-listings-oracle-java-developer-21',
    description:
      'Work on internal cloud tooling and service integrations.\nWrite clean Java code following Oracle guidelines.\nCollaborate with senior developers on design and code reviews.\nBest for 0–1 year engineers with solid OOP principles.',
  },
  {
    id: 'job-22',
    title: 'Data Analyst Intern',
    company: 'CRED',
    location: 'Bengaluru, Karnataka',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['SQL', 'Python', 'Dashboards'],
    source: 'LinkedIn',
    postedDaysAgo: 5,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.linkedin.com/jobs/view/cred-data-analyst-intern-22',
    description:
      'Work with growth teams to analyse credit card spend patterns.\nBuild dashboards to track key user funnels and cohorts.\nPresent simple insights to PMs and marketing partners.\nIdeal for students who enjoy structured problem solving.',
  },
  {
    id: 'job-23',
    title: 'Graduate Engineer Trainee',
    company: 'Wipro',
    location: 'Hyderabad, Telangana',
    mode: 'Onsite',
    experience: '0-1',
    skills: ['Java', 'C#', 'Databases'],
    source: 'Naukri',
    postedDaysAgo: 7,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.naukri.com/job-listings-wipro-get-23',
    description:
      'Participate in classroom and on-the-job training programs.\nSupport delivery teams by handling low-risk tasks and scripts.\nLearn corporate practices around documentation and reviews.\nGreat starting point for CS and IT graduates.',
  },
  {
    id: 'job-24',
    title: 'React Developer (1-3 years)',
    company: 'Paytm',
    location: 'Noida, Uttar Pradesh',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['React', 'Redux', 'TypeScript'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://www.linkedin.com/jobs/view/paytm-react-developer-24',
    description:
      'Own small React modules within the Paytm consumer app.\nWork with designers to refine flows based on user feedback.\nEnsure performance and accessibility on lower-end devices.\nIdeal for developers with 1–3 years of React experience.',
  },
  {
    id: 'job-25',
    title: 'SDE Intern',
    company: 'Flipkart',
    location: 'Bengaluru, Karnataka',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Java', 'Spring', 'Kafka'],
    source: 'LinkedIn',
    postedDaysAgo: 9,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.linkedin.com/jobs/view/flipkart-sde-intern-25',
    description:
      'Join the supply-chain engineering team as an intern.\nHelp build internal tools that track inventory and routing.\nWrite small services under supervision with robust tests.\nBest for students curious about logistics and backend systems.',
  },
  {
    id: 'job-26',
    title: 'Junior Backend Developer',
    company: 'Swiggy',
    location: 'Bengaluru, Karnataka',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Node.js', 'Express', 'MongoDB'],
    source: 'LinkedIn',
    postedDaysAgo: 3,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://www.linkedin.com/jobs/view/swiggy-junior-backend-26',
    description:
      'Build and maintain services related to restaurant onboarding.\nWrite APIs, background jobs, and monitoring hooks.\nCollaborate with product managers and operations teams.\nIdeal for engineers who enjoy fast-moving product work.',
  },
  {
    id: 'job-27',
    title: 'QA Intern',
    company: 'Infosys',
    location: 'Mysuru, Karnataka',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Manual Testing', 'Automation Basics'],
    source: 'Indeed',
    postedDaysAgo: 4,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.indeed.co.in/viewjob-infosys-qa-intern-27',
    description:
      'Learn structured testing methods on enterprise projects.\nCreate and run regression test suites for web applications.\nDocument test evidence and maintain test case repositories.\nGreat for freshers interested in QA automation later.',
  },
  {
    id: 'job-28',
    title: 'Python Developer (Fresher)',
    company: 'TCS',
    location: 'Kolkata, West Bengal',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Python', 'Django', 'REST', 'SQL'],
    source: 'Naukri',
    postedDaysAgo: 5,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.naukri.com/job-listings-tcs-python-developer-28',
    description:
      'Support teams building internal reporting tools.\nWork on simple REST APIs, forms, and admin dashboards.\nFollow TCS coding and security guidelines from day one.\nOpen to freshers with good Python and Django basics.',
  },
  {
    id: 'job-29',
    title: 'React Developer (1-3 years)',
    company: 'Zoho',
    location: 'Chennai, Tamil Nadu',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['React', 'TypeScript', 'Testing Library'],
    source: 'LinkedIn',
    postedDaysAgo: 6,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://www.linkedin.com/jobs/view/zoho-react-developer-29',
    description:
      'Join a product team owning a specific SaaS module.\nImplement UI flows with a focus on clarity and responsiveness.\nWrite unit and integration tests for critical user journeys.\nSuitable for engineers who enjoy product thinking.',
  },
  {
    id: 'job-30',
    title: 'SDE Intern',
    company: 'Freshworks',
    location: 'Chennai, Tamil Nadu',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Java', 'Kotlin', 'REST'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.linkedin.com/jobs/view/freshworks-sde-intern-30',
    description:
      'Work alongside backend engineers on core product APIs.\nHandle low-risk tickets and write automated tests.\nParticipate in pairing sessions and technical reviews.\nWell-suited for students with backend project experience.',
  },
  {
    id: 'job-31',
    title: 'Java Developer (0-1 years)',
    company: 'Capgemini',
    location: 'Pune, Maharashtra',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Java', 'Spring Boot', 'SQL'],
    source: 'Indeed',
    postedDaysAgo: 7,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.indeed.co.in/viewjob-capgemini-java-31',
    description:
      'Join a project team working on enterprise applications.\nFix bugs, write simple modules, and contribute to release notes.\nLearn configuration management and deployment processes.\nGreat for graduates comfortable with Spring basics.',
  },
  {
    id: 'job-32',
    title: 'Data Analyst Intern',
    company: 'Flipkart',
    location: 'Bengaluru, Karnataka',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['SQL', 'Power BI', 'Excel'],
    source: 'LinkedIn',
    postedDaysAgo: 8,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.linkedin.com/jobs/view/flipkart-data-analyst-intern-32',
    description:
      'Analyse merchant and order data to spot anomalies.\nBuild Power BI dashboards for category managers.\nShare simple written summaries alongside charts.\nPerfect for analytical students who like structured work.',
  },
  {
    id: 'job-33',
    title: 'Junior Backend Developer',
    company: 'Razorpay',
    location: 'Bengaluru, Karnataka',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Go', 'PostgreSQL', 'GRPC'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://www.linkedin.com/jobs/view/razorpay-junior-backend-33',
    description:
      'Own small services that support payment reconciliation.\nWrite clear code with strong observability and metrics.\nParticipate in design reviews and postmortems.\nRight for engineers who care about correctness and reliability.',
  },
  {
    id: 'job-34',
    title: 'Frontend Intern',
    company: 'CRED',
    location: 'Bengaluru, Karnataka',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['React', 'CSS', 'Animations'],
    source: 'LinkedIn',
    postedDaysAgo: 9,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.linkedin.com/jobs/view/cred-frontend-intern-34',
    description:
      'Help prototype new UI experiments in a controlled environment.\nTranslate motion specs into subtle, production-ready interactions.\nWork closely with design and Android teams.\nGood for students with a strong sense of visual detail.',
  },
  {
    id: 'job-35',
    title: 'Graduate Engineer Trainee',
    company: 'Cognizant',
    location: 'Kolkata, West Bengal',
    mode: 'Onsite',
    experience: '0-1',
    skills: ['Java', 'Testing', 'SQL'],
    source: 'Naukri',
    postedDaysAgo: 4,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.naukri.com/job-listings-cognizant-get-35',
    description:
      'Move through structured training on Java and testing tools.\nWork on internal projects after completing the academy program.\nShadow senior associates during client interactions.\nIdeal entry-level role for campus graduates.',
  },
  {
    id: 'job-36',
    title: 'Python Developer (Fresher)',
    company: 'IBM India',
    location: 'Bengaluru, Karnataka',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Python', 'APIs', 'Cloud Basics'],
    source: 'Indeed',
    postedDaysAgo: 6,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.indeed.co.in/viewjob-ibm-python-fresher-36',
    description:
      'Support consulting teams by writing Python automation scripts.\nIntegrate with cloud APIs for reporting and configuration.\nDocument scripts clearly for future reuse.\nGood for freshers curious about cloud and automation.',
  },
  {
    id: 'job-37',
    title: 'React Developer (1-3 years)',
    company: 'Oracle India',
    location: 'Hyderabad, Telangana',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['React', 'TypeScript', 'State Management'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://www.linkedin.com/jobs/view/oracle-react-developer-37',
    description:
      'Build UI for internal admin tools used by cloud teams.\nEnsure responsiveness and accessibility across browsers.\nCollaborate with backend teams on API contracts.\nSuited for engineers with a structured approach to UI work.',
  },
  {
    id: 'job-38',
    title: 'SDE Intern',
    company: 'Zoho',
    location: 'Chennai, Tamil Nadu',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['C++', 'Problem Solving', 'Algorithms'],
    source: 'LinkedIn',
    postedDaysAgo: 3,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.linkedin.com/jobs/view/zoho-sde-intern-38',
    description:
      'Solve real-world problems in small backend and systems projects.\nParticipate in weekly problem-solving sessions and reviews.\nWrite efficient code with clear documentation.\nIdeal for students strong in algorithms and C++.',
  },
  {
    id: 'job-39',
    title: 'Junior Backend Developer',
    company: 'Infosys',
    location: 'Bengaluru, Karnataka',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Java', 'Spring Boot', 'REST'],
    source: 'Naukri',
    postedDaysAgo: 5,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://www.naukri.com/job-listings-infosys-junior-backend-39',
    description:
      'Join a digital transformation project for a global client.\nImplement features under guidance and follow coding standards.\nParticipate in defect triage and production support.\nGreat for 1–3 year engineers looking for structured growth.',
  },
  {
    id: 'job-40',
    title: 'Data Analyst Intern',
    company: 'TCS',
    location: 'Mumbai, Maharashtra',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Excel', 'SQL', 'Power BI'],
    source: 'Indeed',
    postedDaysAgo: 7,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.indeed.co.in/viewjob-tcs-data-analyst-intern-40',
    description:
      'Support reporting needs for internal operations teams.\nPrepare daily and weekly reports using Excel and Power BI.\nMaintain data quality through regular checks and reconciliations.\nSuited for commerce and engineering graduates.',
  },
  {
    id: 'job-41',
    title: 'SDE Intern',
    company: 'PhonePe',
    location: 'Bengaluru, Karnataka',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Java', 'Spring', 'Kafka'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.linkedin.com/jobs/view/phonepe-sde-intern-41',
    description:
      'Work on new features for the rewards and offers platform.\nImplement small services and internal tools with strong reviews.\nLearn observability practices like dashboards and alerts.\nBest for students who enjoy backend development.',
  },
  {
    id: 'job-42',
    title: 'React Developer (1-3 years)',
    company: 'Paytm',
    location: 'Bengaluru, Karnataka',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['React', 'Redux', 'REST'],
    source: 'LinkedIn',
    postedDaysAgo: 4,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://www.linkedin.com/jobs/view/paytm-react-developer-42',
    description:
      'Build administrative dashboards used by internal ops teams.\nTranslate wireframes into clean, tested components.\nCollaborate closely with backend and design teams.\nFit for developers with strong React fundamentals.',
  },
  {
    id: 'job-43',
    title: 'Graduate Engineer Trainee',
    company: 'IBM India',
    location: 'Pune, Maharashtra',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Java', 'Cloud Basics'],
    source: 'Naukri',
    postedDaysAgo: 3,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.naukri.com/job-listings-ibm-get-43',
    description:
      'Join consulting teams working on cloud migration projects.\nSupport discovery, documentation, and simple configuration tasks.\nLearn IBM cloud patterns and security guidelines.\nIdeal for graduates curious about consulting and cloud.',
  },
  {
    id: 'job-44',
    title: 'Python Developer (Fresher)',
    company: 'Cognizant',
    location: 'Chennai, Tamil Nadu',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Python', 'APIs', 'Databases'],
    source: 'Indeed',
    postedDaysAgo: 8,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.indeed.co.in/viewjob-cognizant-python-fresher-44',
    description:
      'Support teams building data ingestion and reporting tools.\nImplement simple scripts and microservices as per specifications.\nCollaborate with QA to ensure reliable releases.\nBest for fresh grads with some project experience.',
  },
  {
    id: 'job-45',
    title: 'Junior Backend Developer',
    company: 'Accenture',
    location: 'Bengaluru, Karnataka',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Java', 'Spring Boot', 'REST'],
    source: 'Naukri',
    postedDaysAgo: 6,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://www.naukri.com/job-listings-accenture-junior-backend-45',
    description:
      'Work on integration projects connecting client systems.\nDevelop APIs and assist in migration activities.\nDocument interfaces and support testing teams.\nIdeal for developers who enjoy structured enterprise work.',
  },
  {
    id: 'job-46',
    title: 'SDE Intern',
    company: 'Amazon India',
    location: 'Hyderabad, Telangana',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Java', 'DSA', 'System Design Basics'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.linkedin.com/jobs/view/amazon-sde-intern-46',
    description:
      'Join a small team owning a customer experience feature.\nShip low-risk code with heavy support from mentors.\nParticipate in design discussions and code reviews.\nGreat for candidates strong in problem solving.',
  },
  {
    id: 'job-47',
    title: 'Frontend Intern',
    company: 'Swiggy',
    location: 'Bengaluru, Karnataka',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['React', 'Next.js', 'CSS'],
    source: 'LinkedIn',
    postedDaysAgo: 5,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.linkedin.com/jobs/view/swiggy-frontend-intern-47',
    description:
      'Help maintain internal portals used by ops and city teams.\nImplement UI tweaks and small features in React and Next.js.\nFocus on clarity, performance, and responsiveness.\nPerfect for students with strong front-end portfolios.',
  },
  {
    id: 'job-48',
    title: 'Data Analyst Intern',
    company: 'Paytm',
    location: 'Noida, Uttar Pradesh',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['SQL', 'Excel', 'Reporting'],
    source: 'Indeed',
    postedDaysAgo: 9,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.indeed.co.in/viewjob-paytm-data-analyst-intern-48',
    description:
      'Monitor key metrics across Paytm products.\nPrepare weekly and monthly performance reports.\nWork with business and tech teams to validate data nuances.\nSuitable for freshers who like numbers and structure.',
  },
  {
    id: 'job-49',
    title: 'Graduate Engineer Trainee',
    company: 'Wipro',
    location: 'Chennai, Tamil Nadu',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Java', 'Testing', 'Basics of Cloud'],
    source: 'Naukri',
    postedDaysAgo: 10,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.naukri.com/job-listings-wipro-get-49',
    description:
      'Move between development and testing teams during your first year.\nLearn tools used for CI/CD, monitoring, and ticketing.\nTake ownership of small modules after training.\nGood for graduates open to multiple career paths.',
  },
  {
    id: 'job-50',
    title: 'React Developer (1-3 years)',
    company: 'Freshworks',
    location: 'Chennai, Tamil Nadu',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['React', 'TypeScript', 'CSS Modules'],
    source: 'LinkedIn',
    postedDaysAgo: 3,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://www.linkedin.com/jobs/view/freshworks-react-developer-50',
    description:
      'Contribute to a cross-functional squad owning a core module.\nWrite clear, well-tested React components.\nCollaborate with design on small UX refinements.\nGreat for engineers who enjoy end-user impact.',
  },
  {
    id: 'job-51',
    title: 'Python Developer (Fresher)',
    company: 'Infosys',
    location: 'Pune, Maharashtra',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Python', 'APIs', 'Data Processing'],
    source: 'Indeed',
    postedDaysAgo: 4,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.indeed.co.in/viewjob-infosys-python-fresher-51',
    description:
      'Support teams automating internal workflows and reports.\nBuild small Python utilities with clear logging and error handling.\nCollaborate with stakeholders to refine requirements.\nIdeal for freshers with Python project experience.',
  },
  {
    id: 'job-52',
    title: 'Junior Backend Developer',
    company: 'Flipkart',
    location: 'Bengaluru, Karnataka',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Java', 'Spring Boot', 'MySQL'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://www.linkedin.com/jobs/view/flipkart-junior-backend-52',
    description:
      'Work on catalog and pricing services for the marketplace.\nWrite performant, well-tested APIs and background jobs.\nCollaborate with infra and product teams for smooth releases.\nBest for engineers with strong backend fundamentals.',
  },
  {
    id: 'job-53',
    title: 'Frontend Intern',
    company: 'Juspay',
    location: 'Bengaluru, Karnataka',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['React', 'TypeScript', 'Functional Programming Basics'],
    source: 'LinkedIn',
    postedDaysAgo: 6,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.linkedin.com/jobs/view/juspay-frontend-intern-53',
    description:
      'Work on payment flows that require high attention to detail.\nImplement UI changes in React with a strong focus on safety.\nPair with senior engineers to understand functional programming patterns.\nGreat for students who enjoy deep technical work.',
  },
  {
    id: 'job-54',
    title: 'Data Analyst Intern',
    company: 'Razorpay',
    location: 'Bengaluru, Karnataka',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['SQL', 'Excel', 'Looker'],
    source: 'LinkedIn',
    postedDaysAgo: 7,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.linkedin.com/jobs/view/razorpay-data-analyst-intern-54',
    description:
      'Help maintain core business dashboards for leadership.\nWrite queries against large datasets with attention to correctness.\nSupport ad-hoc analysis requests from different teams.\nSuited for analytical, detail-oriented students.',
  },
  {
    id: 'job-55',
    title: 'Graduate Engineer Trainee',
    company: 'Accenture',
    location: 'Gurugram, Haryana',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Java', 'Testing', 'Cloud Basics'],
    source: 'Naukri',
    postedDaysAgo: 8,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.naukri.com/job-listings-accenture-get-55',
    description:
      'Work on implementation projects for global clients.\nStart in development or testing depending on project needs.\nGain exposure to cloud and integration tools.\nGood for graduates seeking structured training and variety.',
  },
  {
    id: 'job-56',
    title: 'React Developer (1-3 years)',
    company: 'Zoho',
    location: 'Chennai, Tamil Nadu',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['React', 'TypeScript', 'REST'],
    source: 'LinkedIn',
    postedDaysAgo: 5,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://www.linkedin.com/jobs/view/zoho-react-developer-56',
    description:
      'Implement new modules and maintain existing ones across Zoho products.\nWrite reusable, tested components in React and TypeScript.\nCollaborate with cross-functional teams in a product-driven environment.\nIdeal for developers who like long-term product ownership.',
  },
  {
    id: 'job-57',
    title: 'Python Developer (Fresher)',
    company: 'Freshworks',
    location: 'Chennai, Tamil Nadu',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Python', 'Django', 'REST'],
    source: 'Indeed',
    postedDaysAgo: 9,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.indeed.co.in/viewjob-freshworks-python-fresher-57',
    description:
      'Build and maintain small backend services for internal tooling.\nWrite clean Django views, serializers, and tests.\nLearn how incident management and on-call work in practice.\nSuited for freshers with strong Python fundamentals.',
  },
  {
    id: 'job-58',
    title: 'Junior Backend Developer',
    company: 'CRED',
    location: 'Bengaluru, Karnataka',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Kotlin', 'Java', 'Microservices'],
    source: 'LinkedIn',
    postedDaysAgo: 3,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://www.linkedin.com/jobs/view/cred-junior-backend-58',
    description:
      'Join a backend team responsible for rewards and offers.\nWrite microservices with strong observability and resilience.\nParticipate in experiments and A/B test rollouts.\nGreat for engineers who like metrics-driven work.',
  },
  {
    id: 'job-59',
    title: 'SDE Intern',
    company: 'PhonePe',
    location: 'Bengaluru, Karnataka',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Java', 'DSA', 'REST'],
    source: 'LinkedIn',
    postedDaysAgo: 0,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.linkedin.com/jobs/view/phonepe-sde-intern-59',
    description:
      'Contribute to user-facing features with close mentorship.\nFix bugs, write tests, and help with small refactors.\nAttend design and code review sessions.\nIdeal for final-year students with strong CS foundations.',
  },
  {
    id: 'job-60',
    title: 'Data Analyst Intern',
    company: 'Amazon India',
    location: 'Hyderabad, Telangana',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['SQL', 'Excel', 'Python'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.linkedin.com/jobs/view/amazon-data-analyst-intern-60',
    description:
      'Support analytics for marketplace operations.\nPull and clean data from internal sources using SQL.\nBuild simple dashboards and recurring reports.\nBest suited for detail-oriented students comfortable with numbers.',
  },
]

